version: "2"

services:

  plone:
    image: tiberiuichim/energy-union-plone:2.3
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
      - zeo
      - memcached
    ports:
      - "8085:8080"
    # entrypoint: sh -c "tail -f /dev/null"
    environment:
      TZ: "Europe/Copenhagen"
      ZEO_ADDRESS: "zeo:8080"
      ZOPE_MODE: "zeo_client"
    volumes:
    - ./src/:/plone/instance/src/
    - ./docker/site.cfg:/plone/instance/site.cfg
    # - ./data:/data

  #ploneshell:
    # build: ./docker/
    # image: kitconcept/plone.restapi:latest
    #image: tiberiuichim/fise-plone:0.1
    #labels:
      #io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    #depends_on:
      #- zeo
      #- memcached
    #ports:
      #- "8085:8080"
    #entrypoint: sh -c "tail -f /dev/null"
    #environment:
      #TZ: "Europe/Copenhagen"
      #ZEO_ADDRESS: "zeo:8080"
      #ZOPE_MODE: "zeo_client"
    #volumes:
    #- ./src/:/plone/instance/src/
    #- ./docker/site.cfg:/plone/instance/site.cfg
    # - ./data:/data

  memcached:
    image: memcached:1.4.35
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
      - "-m"
      - "2048"

  zeo:
    image: plone:5.2-python2
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
      ZOPE_MODE: "zeo"
    command:
      - zeo
    volumes:
      - ./data:/data
      # - ./data/blobstorage:/data/blobstorage

  frontend:
    image: tiberiuichim/energy_union_frontend:1.0
    environment:
      RAZZLE_API_PATH: "http://localhost:8085/eunion"
      RAZLLE_INTERNAL_API_PATH: "http://plone:8080/eunion"
      PORT: "3000"
    ports:
      - "3000:3000"
      - "3001:3001"
    entrypoint: sh -c "tail -f /dev/null"
    volumes:
      # - ./frontend/entrypoint-dev.sh:/opt/fise/entrypoint.sh
      - ./energy_union_frontend:/opt/energyunion/

# backend demo-forests-p5-plone
# http-request set-path /VirtualHostBase/https/demo-forests-p5.eea.europa.eu:443/fise/VirtualHostRoot/_vh_api/%[path,regsub(\/api,,g)]
