version: "2.1"

services:

  zeo:
    volumes:
      - ./plone-data:/data

  plone:
    volumes:
      - ./src:/plone/instance/src
      - ./backend/site.cfg:/plone/instance/site.cfg
    environment:
      CORS_ALLOW_ORIGIN: "http://localhost:3000,http://localhost:3085"

  frontend:
    volumes:
      - ./frontend:/opt/frontend
      - ./.git:/opt/.git
